USE ROLE FIN_ENT_CHATBOT_POC2;
USE WAREHOUSE FIN_ENT_APP_POC2_WH;
USE DATABASE FIN_ENT_AI_POC2;
USE SCHEMA SEARCH;


CREATE OR REPLACE CORTEX SEARCH SERVICE INVOICE_SEARCH_SVC2
ON CHUNK_TEXT
ATTRIBUTES
  DOCUMENT_ID,
  RELATIVE_PATH,
  CHUNK_TYPE,
  CHUNK_INDEX,
  INVOICE_NUMBER,
  CUSTOMER_NAME,
  DUE_DATE,
  TOTAL_DUE
WAREHOUSE = FIN_ENT_APP_POC2_WH
TARGET_LAG = '5 minutes'
INITIALIZE = ON_CREATE
AS
SELECT
    CHUNK_TEXT,
    DOCUMENT_ID,
    RELATIVE_PATH,
    CHUNK_TYPE,
    CHUNK_INDEX,
    INVOICE_NUMBER,
    CUSTOMER_NAME,
    DUE_DATE,
    TOTAL_DUE
FROM FIN_ENT_AI_POC2.CURATED_DOCS.INVOICE_CHUNK;

/*
CREATE OR REPLACE CORTEX SEARCH SERVICE INVOICE_SEARCH_SVC2
ON CHUNK_TEXT
ATTRIBUTES DOCUMENT_ID, RELATIVE_PATH, CHUNK_INDEX
WAREHOUSE = FIN_ENT_APP_POC2_WH
TARGET_LAG = '5 minutes'
INITIALIZE = ON_CREATE
AS
SELECT
    CHUNK_TEXT,
    DOCUMENT_ID,
    RELATIVE_PATH,
    CHUNK_INDEX
FROM FIN_ENT_AI_POC2.CURATED_DOCS.INVOICE_CHUNK;
*/

--confirm

USE ROLE FIN_ENT_CHATBOT_POC2;
USE DATABASE FIN_ENT_AI_POC2;
USE SCHEMA SEARCH;

DESCRIBE CORTEX SEARCH SERVICE INVOICE_SEARCH_SVC2;


SELECT *
FROM FIN_ENT_AI_POC2.INFORMATION_SCHEMA.CORTEX_SEARCH_SERVICES
WHERE SERVICE_NAME = 'INVOICE_SEARCH_SVC2';


SELECT SNOWFLAKE.CORTEX.SEARCH_PREVIEW(
  'FIN_ENT_AI_POC2.SEARCH.INVOICE_SEARCH_SVC2',
  '{
    "query": "INV-1010 total amount due Summit Health Systems",
    "columns": ["DOCUMENT_ID", "RELATIVE_PATH", "CHUNK_TYPE", "CHUNK_INDEX", "INVOICE_NUMBER", "CUSTOMER_NAME", "DUE_DATE", "TOTAL_DUE"],
    "limit": 8
  }'
) AS SEARCH_RESULTS;


USE ROLE FIN_ENT_CHATBOT_POC2;
USE WAREHOUSE FIN_ENT_APP_POC2_WH;
USE DATABASE FIN_ENT_AI_POC2;
USE SCHEMA SEARCH;

SELECT
    c.CHUNK_TEXT,
    c.DOCUMENT_ID,
    c.RELATIVE_PATH,
    c.CHUNK_INDEX,
    e.INVOICE_NUMBER,
    e.CUSTOMER_NAME,
    e.DUE_DATE,
    e.TOTAL_DUE
FROM FIN_ENT_AI_POC2.CURATED_DOCS.INVOICE_CHUNK c
LEFT JOIN FIN_ENT_AI_POC2.CURATED_DOCS.INVOICE_EXTRACT e
  ON c.DOCUMENT_ID = e.DOCUMENT_ID
LIMIT 20;