USE ROLE FIN_ENT_CHATBOT_POC2;
USE WAREHOUSE FIN_ENT_ETL_POC2_WH;
USE DATABASE FIN_ENT_AI_POC2;
USE SCHEMA CURATED_DOCS;

TRUNCATE TABLE INVOICE_PARSED;

INSERT INTO INVOICE_PARSED (
    DOCUMENT_ID,
    RELATIVE_PATH,
    PARSED_JSON,
    PARSED_TEXT
)
WITH parsed AS (
    SELECT
        REGEXP_SUBSTR(RELATIVE_PATH, '[^/]+$') AS DOCUMENT_ID,
        RELATIVE_PATH,
        AI_PARSE_DOCUMENT(
            TO_FILE('@FIN_ENT_AI_POC2.RAW_DOCS.INVOICE_STAGE_SSE', RELATIVE_PATH),
            OBJECT_CONSTRUCT('mode', 'LAYOUT')
        ) AS DOC_OBJ
    FROM DIRECTORY(@FIN_ENT_AI_POC2.RAW_DOCS.INVOICE_STAGE_SSE)
)
SELECT
    DOCUMENT_ID,
    RELATIVE_PATH,
    DOC_OBJ AS PARSED_JSON,
    DOC_OBJ:content::STRING AS PARSED_TEXT
FROM parsed;


SELECT RELATIVE_PATH
FROM DIRECTORY(@FIN_ENT_AI_POC2.RAW_DOCS.INVOICE_STAGE_SSE)
ORDER BY RELATIVE_PATH;

SELECT AI_PARSE_DOCUMENT(
  TO_FILE('@FIN_ENT_AI_POC2.RAW_DOCS.INVOICE_STAGE_SSE', 'INV-1001.pdf'),
  OBJECT_CONSTRUCT('mode', 'LAYOUT')
);