USE ROLE FIN_ENT_CHATBOT_POC2;
USE WAREHOUSE FIN_ENT_ETL_POC2_WH;
USE DATABASE FIN_ENT_AI_POC2;

-- 1. Confirm files exist on the new SSE stage -- should be 36 rows
SELECT COUNT(*) AS STAGED_FILES
FROM DIRECTORY(@FIN_ENT_AI_POC2.RAW_DOCS.INVOICE_STAGE_SSE);

-- 2. Confirm parsed document rows were created -- should be 36 rows
SELECT COUNT(*) AS PARSED_DOCS
FROM FIN_ENT_AI_POC2.CURATED_DOCS.INVOICE_PARSED;

-- 3. Confirm extracted rows were created -- should be 36 rows
SELECT COUNT(*) AS EXTRACTED_DOCS
FROM FIN_ENT_AI_POC2.CURATED_DOCS.INVOICE_EXTRACT;

-- 4. Confirm chunk rows were created
SELECT COUNT(*) AS CHUNKS
FROM FIN_ENT_AI_POC2.CURATED_DOCS.INVOICE_CHUNK;

-- 5. Inspect extracted invoice fields
SELECT
    DOCUMENT_ID,
    INVOICE_NUMBER,
    CUSTOMER_NAME,
    INVOICE_DATE,
    DUE_DATE,
    TOTAL_DUE,
    PAYMENT_TERMS,
    PO_NUMBER
FROM FIN_ENT_AI_POC2.CURATED_DOCS.INVOICE_EXTRACT
ORDER BY INVOICE_NUMBER;

-- 6. Preview parsed text for a few invoices
SELECT
    DOCUMENT_ID,
    RELATIVE_PATH,
    LEFT(PARSED_TEXT, 1000) AS PARSED_TEXT_PREVIEW
FROM FIN_ENT_AI_POC2.CURATED_DOCS.INVOICE_PARSED
ORDER BY DOCUMENT_ID
LIMIT 5;

-- 7. Preview generated chunks
SELECT
    DOCUMENT_ID,
    CHUNK_INDEX,
    CHUNK_TEXT
FROM FIN_ENT_AI_POC2.CURATED_DOCS.INVOICE_CHUNK
ORDER BY DOCUMENT_ID, CHUNK_INDEX
LIMIT 20;