USE ROLE FIN_ENT_CHATBOT_POC2;
USE WAREHOUSE FIN_ENT_ETL_POC2_WH;
USE DATABASE FIN_ENT_AI_POC2;

USE SCHEMA CURATED_FINANCE;
CREATE OR REPLACE VIEW INVOICE_RECON_V AS
SELECT
    i.INVOICE_ID,
    i.CUSTOMER_ID,
    c.CUSTOMER_NAME AS ERP_CUSTOMER_NAME,
    x.CUSTOMER_NAME AS DOC_CUSTOMER_NAME,
    i.INVOICE_DATE AS ERP_INVOICE_DATE,
    x.INVOICE_DATE AS DOC_INVOICE_DATE,
    i.DUE_DATE AS ERP_DUE_DATE,
    x.DUE_DATE AS DOC_DUE_DATE,
    c.PAYMENT_TERMS AS ERP_PAYMENT_TERMS,
    x.PAYMENT_TERMS AS DOC_PAYMENT_TERMS,
    i.AMOUNT AS ERP_AMOUNT,
    x.TOTAL_DUE AS DOC_AMOUNT,
    i.CURRENCY AS ERP_CURRENCY,
    x.CURRENCY AS DOC_CURRENCY,
    x.PO_NUMBER AS DOC_PO_NUMBER,
    x.DOCUMENT_ID,
    x.RELATIVE_PATH,

    CASE
        WHEN UPPER(TRIM(c.CUSTOMER_NAME)) = UPPER(TRIM(x.CUSTOMER_NAME)) THEN 'MATCH'
        ELSE 'MISMATCH'
    END AS CUSTOMER_NAME_MATCH,

    CASE
        WHEN i.INVOICE_DATE = x.INVOICE_DATE THEN 'MATCH'
        ELSE 'MISMATCH'
    END AS INVOICE_DATE_MATCH,

    CASE
        WHEN i.DUE_DATE = x.DUE_DATE THEN 'MATCH'
        ELSE 'MISMATCH'
    END AS DUE_DATE_MATCH,

    CASE
        WHEN UPPER(TRIM(c.PAYMENT_TERMS)) = UPPER(TRIM(x.PAYMENT_TERMS)) THEN 'MATCH'
        ELSE 'MISMATCH'
    END AS PAYMENT_TERMS_MATCH,

    CASE
        WHEN i.CURRENCY = x.CURRENCY THEN 'MATCH'
        ELSE 'MISMATCH'
    END AS CURRENCY_MATCH,

    CASE
        WHEN ABS(COALESCE(i.AMOUNT, 0) - COALESCE(x.TOTAL_DUE, 0)) < 0.01 THEN 'MATCH'
        ELSE 'MISMATCH'
    END AS AMOUNT_MATCH,

    CASE
        WHEN x.PO_NUMBER IS NOT NULL THEN 'PRESENT'
        ELSE 'MISSING'
    END AS DOC_PO_NUMBER_STATUS,

    CASE
        WHEN
            UPPER(TRIM(c.CUSTOMER_NAME)) = UPPER(TRIM(x.CUSTOMER_NAME))
            AND i.INVOICE_DATE = x.INVOICE_DATE
            AND i.DUE_DATE = x.DUE_DATE
            AND UPPER(TRIM(c.PAYMENT_TERMS)) = UPPER(TRIM(x.PAYMENT_TERMS))
            AND i.CURRENCY = x.CURRENCY
            AND ABS(COALESCE(i.AMOUNT, 0) - COALESCE(x.TOTAL_DUE, 0)) < 0.01
        THEN 'MATCH'
        ELSE 'MISMATCH'
    END AS OVERALL_RECON_STATUS,

    CASE
        WHEN x.INVOICE_NUMBER IS NULL THEN 'NO_DOCUMENT_EXTRACT'
        WHEN
            UPPER(TRIM(c.CUSTOMER_NAME)) = UPPER(TRIM(x.CUSTOMER_NAME))
            AND i.INVOICE_DATE = x.INVOICE_DATE
            AND i.DUE_DATE = x.DUE_DATE
            AND UPPER(TRIM(c.PAYMENT_TERMS)) = UPPER(TRIM(x.PAYMENT_TERMS))
            AND i.CURRENCY = x.CURRENCY
            AND ABS(COALESCE(i.AMOUNT, 0) - COALESCE(x.TOTAL_DUE, 0)) < 0.01
        THEN 'ERP_AND_DOC_MATCH'
        ELSE
            RTRIM(
                CASE WHEN UPPER(TRIM(c.CUSTOMER_NAME)) <> UPPER(TRIM(x.CUSTOMER_NAME)) THEN 'CUSTOMER_NAME,' ELSE '' END ||
                CASE WHEN i.INVOICE_DATE <> x.INVOICE_DATE THEN 'INVOICE_DATE,' ELSE '' END ||
                CASE WHEN i.DUE_DATE <> x.DUE_DATE THEN 'DUE_DATE,' ELSE '' END ||
                CASE WHEN UPPER(TRIM(c.PAYMENT_TERMS)) <> UPPER(TRIM(x.PAYMENT_TERMS)) THEN 'PAYMENT_TERMS,' ELSE '' END ||
                CASE WHEN i.CURRENCY <> x.CURRENCY THEN 'CURRENCY,' ELSE '' END ||
                CASE WHEN ABS(COALESCE(i.AMOUNT, 0) - COALESCE(x.TOTAL_DUE, 0)) >= 0.01 THEN 'AMOUNT,' ELSE '' END ||
                CASE WHEN x.PO_NUMBER IS NOT NULL THEN 'PO_NUMBER_PRESENT_IN_DOC,' ELSE '' END,
                ','
            )
    END AS RECON_EXCEPTION_DETAIL

FROM FIN_ENT_AI_POC2.RAW_FINANCE.INVOICE_RAW i
JOIN FIN_ENT_AI_POC2.RAW_FINANCE.CUSTOMER_RAW c
  ON i.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN FIN_ENT_AI_POC2.CURATED_DOCS.INVOICE_EXTRACT x
  ON i.INVOICE_ID = x.INVOICE_NUMBER;