USE ROLE FIN_ENT_CHATBOT_POC2;
USE WAREHOUSE FIN_ENT_ETL_POC2_WH;
USE DATABASE FIN_ENT_AI_POC2;

SELECT *
FROM FIN_ENT_AI_POC2.CURATED_FINANCE.OPEN_ACCT_RECV_BY_INV_V
ORDER BY OPEN_AMOUNT DESC, INVOICE_ID
LIMIT 20;

SELECT *
FROM FIN_ENT_AI_POC2.CURATED_FINANCE.CUSTOMER_REVENUE_MTH_V
ORDER BY CUSTOMER_ID, REVENUE_MONTH;

SELECT *
FROM FIN_ENT_AI_POC2.CURATED_FINANCE.ACCT_RECV_AGING
ORDER BY DAYS_PAST_DUE DESC, OPEN_AMOUNT DESC
LIMIT 20;

SELECT *
FROM FIN_ENT_AI_POC2.CURATED_FINANCE.CUSTOMER_BALANCE_SUM_V
ORDER BY TOTAL_OPEN_AMOUNT DESC;

SELECT
    OVERALL_RECON_STATUS,
    COUNT(*) AS INVOICE_COUNT
FROM FIN_ENT_AI_POC2.CURATED_FINANCE.INVOICE_RECON_V
GROUP BY OVERALL_RECON_STATUS
ORDER BY OVERALL_RECON_STATUS;

SELECT
    INVOICE_ID,
    ERP_CUSTOMER_NAME,
    DOC_CUSTOMER_NAME,
    ERP_INVOICE_DATE,
    DOC_INVOICE_DATE,
    ERP_DUE_DATE,
    DOC_DUE_DATE,
    ERP_PAYMENT_TERMS,
    DOC_PAYMENT_TERMS,
    ERP_AMOUNT,
    DOC_AMOUNT,
    DOC_PO_NUMBER_STATUS,
    OVERALL_RECON_STATUS,
    RECON_EXCEPTION_DETAIL
FROM FIN_ENT_AI_POC2.CURATED_FINANCE.INVOICE_RECON_V
WHERE OVERALL_RECON_STATUS = 'MISMATCH'
ORDER BY INVOICE_ID;


SELECT
    INVOICE_ID,
    ERP_CUSTOMER_NAME,
    DOC_CUSTOMER_NAME,
    ERP_DUE_DATE,
    DOC_DUE_DATE,
    ERP_PAYMENT_TERMS,
    DOC_PAYMENT_TERMS,
    ERP_AMOUNT,
    DOC_AMOUNT,
    DOC_PO_NUMBER_STATUS,
    RECON_EXCEPTION_DETAIL
FROM FIN_ENT_AI_POC2.CURATED_FINANCE.INVOICE_RECON_V
WHERE INVOICE_ID IN ('INV-1002', 'INV-1010', 'INV-1023', 'INV-1032', 'INV-1035')
ORDER BY INVOICE_ID;



USE ROLE FIN_ENT_CHATBOT_POC2;
USE WAREHOUSE FIN_ENT_ETL_POC2_WH;
USE DATABASE FIN_ENT_AI_POC2;

SELECT
    CUSTOMER_NAME_MATCH,
    COUNT(*) AS CNT
FROM FIN_ENT_AI_POC2.CURATED_FINANCE.INVOICE_RECON_V
GROUP BY CUSTOMER_NAME_MATCH
ORDER BY CUSTOMER_NAME_MATCH; --36

SELECT
    INVOICE_DATE_MATCH,
    COUNT(*) AS CNT
FROM FIN_ENT_AI_POC2.CURATED_FINANCE.INVOICE_RECON_V
GROUP BY INVOICE_DATE_MATCH
ORDER BY INVOICE_DATE_MATCH;  --1

SELECT
    DUE_DATE_MATCH,
    COUNT(*) AS CNT
FROM FIN_ENT_AI_POC2.CURATED_FINANCE.INVOICE_RECON_V
GROUP BY DUE_DATE_MATCH
ORDER BY DUE_DATE_MATCH; --2

SELECT
    PAYMENT_TERMS_MATCH,
    COUNT(*) AS CNT
FROM FIN_ENT_AI_POC2.CURATED_FINANCE.INVOICE_RECON_V
GROUP BY PAYMENT_TERMS_MATCH
ORDER BY PAYMENT_TERMS_MATCH; --2

SELECT
    CURRENCY_MATCH,
    COUNT(*) AS CNT
FROM FIN_ENT_AI_POC2.CURATED_FINANCE.INVOICE_RECON_V
GROUP BY CURRENCY_MATCH
ORDER BY CURRENCY_MATCH; --1

SELECT
    AMOUNT_MATCH,
    COUNT(*) AS CNT
FROM FIN_ENT_AI_POC2.CURATED_FINANCE.INVOICE_RECON_V
GROUP BY AMOUNT_MATCH
ORDER BY AMOUNT_MATCH; --36


SELECT
    DOCUMENT_ID,
    INVOICE_NUMBER,
    CUSTOMER_NAME,
    INVOICE_DATE,
    DUE_DATE,
    PAYMENT_TERMS,
    CURRENCY,
    TOTAL_DUE,
    PO_NUMBER
FROM FIN_ENT_AI_POC2.CURATED_DOCS.INVOICE_EXTRACT
ORDER BY INVOICE_NUMBER
LIMIT 20;


SELECT
    INVOICE_ID,
    CUSTOMER_NAME_MATCH,
    INVOICE_DATE_MATCH,
    DUE_DATE_MATCH,
    PAYMENT_TERMS_MATCH,
    CURRENCY_MATCH,
    AMOUNT_MATCH,
    DOC_PO_NUMBER_STATUS,
    OVERALL_RECON_STATUS,
    RECON_EXCEPTION_DETAIL
FROM FIN_ENT_AI_POC2.CURATED_FINANCE.INVOICE_RECON_V
ORDER BY INVOICE_ID;


SELECT
    INVOICE_ID,
    ERP_CUSTOMER_NAME,
    DOC_CUSTOMER_NAME,
    ERP_INVOICE_DATE,
    DOC_INVOICE_DATE,
    ERP_DUE_DATE,
    DOC_DUE_DATE,
    ERP_PAYMENT_TERMS,
    DOC_PAYMENT_TERMS,
    ERP_AMOUNT,
    DOC_AMOUNT,
    DOC_PO_NUMBER_STATUS,
    RECON_EXCEPTION_DETAIL
FROM FIN_ENT_AI_POC2.CURATED_FINANCE.INVOICE_RECON_V
WHERE OVERALL_RECON_STATUS = 'MISMATCH'
ORDER BY INVOICE_ID;